### PR TITLE
hal: infineon: Add XMC4800 mcu

### PR DESCRIPTION
**Pull request by talih0**
From Infineon DAVE IDE.

Signed-off-by: Andriy Gelman <andriy.gelman@gmail.com>

### CODE REVIEW

**Comment by talih0** [comment]
ping

**Comment by talih0** [comment]
Hi @parthitce, have you had a chance to look at this PR?

**Comment by parthitce** [comment]
> Hi @parthitce, have you had a chance to look at this PR?

Not yet, will do it during this week.

**Comment by talih0** [comment]
ping

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
