### PR TITLE
hal: infineon: Add options for compiling different modules

### PR DESCRIPTION
**Pull request by talih0**
To support future drivers in zephyr.

Signed-off-by: Andriy Gelman <andriy.gelman@gmail.com>

### CODE REVIEW

**Comment by talih0** [comment]
ping

**Comment by talih0** [comment]
> There needs to be a Zephyr-side that pulls and tests this PR.

@stephanosio The zephyr side will not use all the options. I'll be posting a zephyr PR flash and spi that will use
CONFIG_HAS_XMCLIB_FLASH and CONFIG_HAS_XMCLIB_SPI. 

Do I need to do a separate hal PR for each option?

**Comment by ifyall** [comment]
Other than wanting to see the test PR(s) for the SPI and Flash, this looks good. I will approve in anticipation of such PR(s).

**Comment by parthitce** [comment]
@talih0 Should we need to add all the drivers in a single go?

**Comment by talih0** [comment]
> @talih0 Should we need to add all the drivers in a single go?

Sure, all the options are not needed at the moment.., but also I do not want to keep on bothering you and other reviewers over trivial patches.

**Pull request merged**
